import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Diffender — 1-minute demo",
  description:
    "Watch Diffender defend a design system: live token extraction, per-commit Design Guardrails verdicts with one-click fixes, and AI-generated demo videos of your real app. This video was generated by Diffender itself.",
  openGraph: {
    title: "Diffender — 1-minute demo",
    description:
      "An AI-native design system that detects drift, proposes the fix, and films the demo. Made with Diffender — this video included.",
    images: ["/videos/walktour.jpg"],
  },
};

export default function DemoPage() {
  return (
    <main className="min-h-screen bg-[#faf9f7] text-[#1c1917] flex flex-col items-center justify-center px-4 py-10">
      <div className="w-full max-w-5xl flex flex-col items-center gap-6">
        <div className="flex items-center gap-2 text-[#e8500f] font-semibold tracking-wide">
          <span className="text-xl">◆</span>
          <span>Diffender</span>
        </div>

        <h1 className="text-center text-3xl sm:text-5xl font-extrabold tracking-tight">
          Keep your product on-brand,{" "}
          <span className="text-[#e8500f]">every commit.</span>
        </h1>

        <p className="text-center text-sm sm:text-base text-[#57534e] max-w-2xl">
          One minute. Live design-system extraction, Design Guardrails verdicts
          on every commit, one-click fixes — and a demo video engine.{" "}
          <span className="text-[#e8500f] font-medium">
            This video was generated by Diffender itself.
          </span>
        </p>

        <div className="w-full rounded-2xl overflow-hidden border border-black/10 shadow-[0_24px_80px_-24px_rgba(232,80,15,0.25)] bg-black">
          <video
            className="w-full h-auto"
            src="/videos/walktour.mp4"
            poster="/videos/walktour.jpg"
            controls
            playsInline
            preload="metadata"
          />
        </div>

        <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
          <Link
            href="/"
            className="rounded-full bg-[#FF5A1F] px-5 py-2.5 text-sm font-bold text-white shadow-[0_8px_24px_-8px_#FF5A1F99] hover:opacity-90 transition"
          >
            Try the app →
          </Link>
          <a
            href="https://github.com/edouardfoussier/raise-hack"
            target="_blank"
            rel="noreferrer"
            className="rounded-full border border-black/15 px-5 py-2.5 text-sm font-semibold text-[#1c1917] hover:bg-black/5 transition"
          >
            GitHub repo
          </a>
        </div>

        <p className="text-xs text-[#a8a29e] pt-2">
          Built by Edouard · RAISE Summit Hackathon 2026 · Cursor track (remote)
        </p>
      </div>
    </main>
  );
}
